# Extracting MIMIC Data

## Environment Setup

In [1]:
import time
import pymysql
import getpass
import pickle as pkl
import pandas as pd
from _collections import OrderedDict

## Query List

#### Construct a list of queries that we will want to run.

In [2]:
queryList = OrderedDict([('PNA-POS', './queries/PNA-POS-Mimic2.sql'), ('PNA-NEG','./queries/PNA-NEG-Mimic2.sql')])

In [6]:
queryList = OrderedDict([('PNA-POS', './queries/PNA-POS-Mimic2-local.sql'), ('PNA-NEG','./queries/PNA-NEG-Mimic2-local.sql')])

## MIMIC Database Connection

#### Make a connection to the MIMIC database and get a cursor for record processing.

In [3]:
conn = pymysql.connect(host="mysql", 
                       port = 3306, user="jovyan", 
                       passwd=getpass.getpass("Enter MySQL passwd for jovyan"), db='mimic2')
cur = conn.cursor()

Enter MySQL passwd for jovyan········

In [7]:
conn = pymysql.connect(host="localhost", 
                       port = 3306, user="jferraro", 
                       passwd=getpass.getpass("Enter MySQL passwd "), db='mimic')
cur = conn.cursor()

Enter MySQL passwd ········

## Retrieve our Data

#### For each query we will retrieve the data and build an ordered dictionary containing our data.

In [4]:
queries = []

for key in queryList:
    count = 1
    file = open(queryList[key], 'r')
    query = file.read()
    print("execute query: " + key)
    %time cur.execute(query)
    queries.append(query)

corpus = pd.concat([pd.read_sql_query(q, conn) for q in queries])
print(corpus.head())

conn.close()

execute query: PNA-POS
CPU times: user 53.8 ms, sys: 2.53 ms, total: 56.3 ms
Wall time: 1.27 s
execute query: PNA-NEG
CPU times: user 382 ms, sys: 199 ms, total: 581 ms
Wall time: 3.08 s
                                                text
0  \n\n\n     DATE: [**2996-12-2**] 10:25 AM\n   ...
1  \n\n\n     DATE: [**2850-2-14**] 10:22 PM\n   ...
2  \n\n\n     DATE: [**2631-10-3**] 9:52 AM\n    ...
3  \n\n\n     DATE: [**2584-11-21**] 11:17 AM\n  ...
4  \n\n\n     DATE: [**2584-11-21**] 11:17 AM\n  ...

## Safestore the Data

#### We will serialize the ordered dictionary structure out to disk. This way we will not have to rebuild our data every time we want to tray a new model. It is a convenience thing....

In [5]:
file = open('pna-corpus.pkl','wb')
pkl.dump(corpus, file)
file.close()
print("Done!")

Done!

In [6]:
corpus["label]

                                                   text
0     \n\n\n     DATE: [**2996-12-2**] 10:25 AM\n   ...
1     \n\n\n     DATE: [**2850-2-14**] 10:22 PM\n   ...
2     \n\n\n     DATE: [**2631-10-3**] 9:52 AM\n    ...
3     \n\n\n     DATE: [**2584-11-21**] 11:17 AM\n  ...
4     \n\n\n     DATE: [**2584-11-21**] 11:17 AM\n  ...
5     \n\n\n     DATE: [**2584-11-21**] 11:17 AM\n  ...
6     \n\n\n     DATE: [**2996-12-3**] 4:26 PM\n    ...
7     \n\n\n     DATE: [**2996-12-3**] 4:26 PM\n    ...
8     \n\n\n     DATE: [**3327-5-12**] 2:57 AM\n    ...
9     \n\n\n     DATE: [**3327-5-12**] 2:57 AM\n    ...
10    \n\n\n     DATE: [**3191-10-25**] 8:05 AM\n   ...
11    \n\n\n     DATE: [**3325-2-25**] 11:13 AM\n   ...
12    \n\n\n     DATE: [**3387-7-21**] 8:30 PM\n    ...
13    \n\n\n     DATE: [**3387-7-21**] 8:30 PM\n    ...
14    \n\n\n     DATE: [**3387-7-21**] 8:30 PM\n    ...
15    \n\n\n     DATE: [**3117-9-2**] 12:46 AM\n    ...
16    \n\n\n     DATE: [**2693-4-17**] 5:04 PM\n    ...
17    \n\n\n     DATE: [**2693-4-17**] 5:04 PM\n    ...
18    \n\n\n     DATE: [**2693-4-17**] 5:04 PM\n    ...
19    \n\n\n     DATE: [**3414-4-2**] 3:10 PM\n     ...
20    \n\n\n     DATE: [**3414-4-2**] 3:10 PM\n     ...
21    \n\n\n     DATE: [**2533-5-20**] 5:05 PM\n    ...
22    \n\n\n     DATE: [**3227-5-6**] 3:53 PM\n     ...
23    \n\n\n     DATE: [**3133-2-3**] 6:18 AM\n     ...
24    \n\n\n     DATE: [**2824-10-17**] 5:02 PM\n   ...
25    \n\n\n     DATE: [**2824-10-17**] 5:02 PM\n   ...
26    \n\n\n     DATE: [**3325-2-22**] 10:09 PM\n   ...
27    \n\n\n     DATE: [**3325-3-8**] 2:41 PM\n     ...
28    \n\n\n     DATE: [**3206-4-20**] 9:51 AM\n    ...
29    \n\n\n     DATE: [**3117-9-13**] 11:16 AM\n   ...
...                                                 ...
9970  \n\n\n     DATE: [**3259-8-17**] 2:32 PM\n    ...
9971  \n\n\n     DATE: [**3259-8-20**] 8:59 AM\n    ...
9972  \n\n\n     DATE: [**3259-8-21**] 9:46 AM\n    ...
9973  \n\n\n     DATE: [**3259-8-23**] 9:24 AM\n    ...
9974  \n\n\n     DATE: [**3259-8-23**] 3:43 PM\n    ...
9975  \n\n\n     DATE: [**3259-8-23**] 3:43 PM\n    ...
9976  \n\n\n     DATE: [**3259-8-23**] 8:06 PM\n    ...
9977  \n\n\n     DATE: [**3259-8-24**] 3:30 PM\n    ...
9978  \n\n\n     DATE: [**3259-8-25**] 3:32 PM\n    ...
9979  \n\n\n     DATE: [**3259-8-25**] 3:32 PM\n    ...
9980  \n\n\n     DATE: [**3259-8-26**] 9:47 AM\n    ...
9981  \n\n\n     DATE: [**3259-8-27**] 4:31 PM\n    ...
9982  \n\n\n     DATE: [**3259-8-29**] 10:43 AM\n   ...
9983  \n\n\n     DATE: [**3259-8-29**] 3:59 PM\n    ...
9984  \n\n\n     DATE: [**3259-8-30**] 11:45 AM\n   ...
9985  \n\n\n     DATE: [**3259-9-2**] 2:59 PM\n     ...
9986  \n\n\n     DATE: [**3149-12-5**] 7:15 PM\n    ...
9987  \n\n\n     DATE: [**3149-12-5**] 7:15 PM\n    ...
9988  \n\n\n     DATE: [**3149-12-5**] 7:15 PM\n    ...
9989  \n\n\n     DATE: [**3149-12-5**] 7:15 PM\n    ...
9990  \n\n\n     DATE: [**3149-12-5**] 7:15 PM\n    ...
9991  \n\n\n     DATE: [**3149-12-5**] 7:14 PM\n    ...
9992  \n\n\n     DATE: [**3149-12-5**] 7:14 PM\n    ...
9993  \n\n\n     DATE: [**3149-12-5**] 7:14 PM\n    ...
9994  \n\n\n     DATE: [**3149-12-5**] 7:14 PM\n    ...
9995  \n\n\n     DATE: [**3149-12-5**] 10:50 PM\n   ...
9996  \n\n\n     DATE: [**3149-12-5**] 7:47 PM\n    ...
9997  \n\n\n     DATE: [**3149-12-5**] 7:47 PM\n    ...
9998  \n\n\n     DATE: [**3149-12-5**] 7:47 PM\n    ...
9999  \n\n\n     DATE: [**3149-12-5**] 6:51 PM\n    ...

[11108 rows x 1 columns]